services:
  - type: web
    name: wework-mcp-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python wework_mcp_server.py
    envVars:
      - key: WEWORK_ACCESS_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.0
    healthCheckPath: /health
